// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf6YKzjT2PVr_KJbzBpSXdhY_q2lXRsW8',
    appId: '1:811446816301:web:647cd34e8217aecac972a4',
    messagingSenderId: '811446816301',
    projectId: 'diaryapp-56f8c',
    authDomain: 'diaryapp-56f8c.firebaseapp.com',
    storageBucket: 'diaryapp-56f8c.firebasestorage.app',
    measurementId: 'G-J308C41QBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE48mwgsSpDhWN8t3U0VF-Bcsa9ZRSjts',
    appId: '1:811446816301:android:dbc4ee581412776bc972a4',
    messagingSenderId: '811446816301',
    projectId: 'diaryapp-56f8c',
    storageBucket: 'diaryapp-56f8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1Rs4kzuUlff6-nZ46vrb3RUoL9u5t5FE',
    appId: '1:811446816301:ios:e316432ee8a00842c972a4',
    messagingSenderId: '811446816301',
    projectId: 'diaryapp-56f8c',
    storageBucket: 'diaryapp-56f8c.firebasestorage.app',
    iosClientId: '811446816301-gj44ek46125o2r3a7u2tnubseods6vb0.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1Rs4kzuUlff6-nZ46vrb3RUoL9u5t5FE',
    appId: '1:811446816301:ios:e316432ee8a00842c972a4',
    messagingSenderId: '811446816301',
    projectId: 'diaryapp-56f8c',
    storageBucket: 'diaryapp-56f8c.firebasestorage.app',
    iosClientId: '811446816301-gj44ek46125o2r3a7u2tnubseods6vb0.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf6YKzjT2PVr_KJbzBpSXdhY_q2lXRsW8',
    appId: '1:811446816301:web:647cd34e8217aecac972a4',
    messagingSenderId: '811446816301',
    projectId: 'diaryapp-56f8c',
    authDomain: 'diaryapp-56f8c.firebaseapp.com',
    storageBucket: 'diaryapp-56f8c.firebasestorage.app',
    measurementId: 'G-J308C41QBJ',
  );
}